version: '2.2'
services:
  api:
    container_name: myapp
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - elasticsearch
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - '8000:3000'
    command: ['node', 'dist/main.js']

  # redis:
  #   image: redis
  #   container_name: ess-redis
  #   ports:
  #     - '6379:6379'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  microservice:
    container_name: microservice
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      NODE_ENV: development
    command: ['node', 'dist/listener.js']

volumes:
  elasticsearch-data:
    driver: local
